development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  session_key: spree_development

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  session_key: spree_test
  
production:
  adapter: mysql
  database: spree_production 
  username: root 
  password:  
  host: localhost